# Generated by Django 3.0.5 on 2020-04-12 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_role_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('connection_string', models.TextField()),
                ('connection_id', models.CharField(max_length=256)),
                ('connection_password', models.CharField(max_length=512)),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.ConnectionType')),
            ],
        ),
    ]
