# Generated by Django 3.0.5 on 2020-04-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_connection_connectiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ConnectionType'),
        ),
    ]
