# Generated by Django 3.0.5 on 2020-04-13 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200412_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PciDss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='BaselineConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_app_cloud', models.IntegerField()),
                ('per_bus_act_outsource', models.IntegerField()),
                ('per_it_outsource', models.IntegerField()),
                ('org_scale', models.IntegerField()),
                ('global_footprint', models.BooleanField()),
                ('dom_loc_workforce', models.IntegerField()),
                ('priv_reg_app', models.BooleanField()),
                ('industry_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.IndustryType')),
                ('pci_dss', models.ManyToManyField(to='api.PciDss')),
            ],
        ),
    ]
