# Generated by Django 3.0.5 on 2020-04-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_baselineconfiguration_industrytype_pcidss'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col1', models.CharField(blank=True, default='', max_length=256)),
                ('col2', models.CharField(blank=True, default='', max_length=256)),
                ('col3', models.CharField(blank=True, default='', max_length=256)),
                ('col4', models.CharField(blank=True, default='', max_length=256)),
                ('col5', models.CharField(blank=True, default='', max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='industrytype',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='pcidss',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
